import express from 'express';
import cors from 'cors';
import OpenAI from 'openai';
import fs from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { createServer } from 'node:http';
import { raceAdvice } from './racing.js';
import { attachMultiplayer } from './multiplayer.js';

const app=express();app.use(cors());app.use(express.json({limit:'1mb'}));
const WORKSPACE_ROOT=path.resolve(process.env.WORKSPACE_ROOT||'./workspace');const BUILD_COMMAND=process.env.BUILD_COMMAND||'npm test';const DATA_DIR=path.resolve(process.env.RACING_DATA_DIR||'./data');const LEADERBOARD_FILE=path.join(DATA_DIR,'racing-leaderboard.json');const PROFILE_FILE=path.join(DATA_DIR,'racing-profiles.json');
function getClient(){if(!process.env.OPENAI_API_KEY)throw new Error('OPENAI_API_KEY is not configured');return new OpenAI({apiKey:process.env.OPENAI_API_KEY})}
async function readJson(file,fallback){try{return JSON.parse(await fs.readFile(file,'utf8'))}catch{return fallback}}async function writeJson(file,data){await fs.mkdir(DATA_DIR,{recursive:true});await fs.writeFile(file,JSON.stringify(data,null,2),'utf8')}
function safePath(p){const target=path.resolve(WORKSPACE_ROOT,p||'');if(target!==WORKSPACE_ROOT&&!target.startsWith(`${WORKSPACE_ROOT}${path.sep}`))throw new Error('Path is outside the allowed workspace');return target}
function runCommand(command,cwd,timeoutMs=120000){return new Promise(resolve=>{const child=spawn(command,{cwd,shell:true,env:process.env});let stdout='',stderr='',timedOut=false;const timer=setTimeout(()=>{timedOut=true;child.kill('SIGTERM')},timeoutMs);child.stdout.on('data',d=>stdout+=d);child.stderr.on('data',d=>stderr+=d);child.on('close',code=>{clearTimeout(timer);resolve({ok:!timedOut&&code===0,code,timedOut,stdout,stderr})});child.on('error',e=>{clearTimeout(timer);resolve({ok:false,code:null,timedOut,stdout,stderr:String(e)})})})}
async function analyzeError(instruction,errorLog){const client=getClient();const r=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6',input:[{role:'system',content:'Return concise JSON with diagnosis, likelyFiles, patchPlan, verificationSteps. Do not claim to have applied a fix.'},{role:'user',content:JSON.stringify({instruction,errorLog})}]});return r.output_text}
app.get('/',(_q,res)=>res.json({ok:true,service:'LUMIRA AI backend'}));app.get('/health',(_q,res)=>res.json({ok:true,service:'ai-developer-workspace'}));
app.post('/api/race-advice',(req,res)=>{try{res.json({ok:true,...raceAdvice(req.body||{})})}catch(e){res.status(400).json({ok:false,error:e.message||'Race advice failed'})}});
app.get('/api/racing/leaderboard',async(req,res)=>{try{const limit=Math.min(Math.max(Number(req.query.limit)||20,1),100);const rows=await readJson(LEADERBOARD_FILE,[]);rows.sort((a,b)=>(Number(b.score)||0)-(Number(a.score)||0));res.json({ok:true,entries:rows.slice(0,limit)})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/racing/score',async(req,res)=>{try{const name=String(req.body?.name||'Player').trim().slice(0,24)||'Player';const score=Math.max(0,Math.floor(Number(req.body?.score)||0));const track=String(req.body?.track||'Neon City').slice(0,40);const car=String(req.body?.car||'Azure').slice(0,24);const rows=await readJson(LEADERBOARD_FILE,[]);rows.push({name,score,track,car,createdAt:new Date().toISOString()});rows.sort((a,b)=>b.score-a.score);await writeJson(LEADERBOARD_FILE,rows.slice(0,500));res.json({ok:true,rank:rows.findIndex(r=>r.name===name&&r.score===score)+1})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.get('/api/racing/profile/:playerId',async(req,res)=>{const id=String(req.params.playerId).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,48);const profiles=await readJson(PROFILE_FILE,{});res.json({ok:true,profile:profiles[id]||{playerId:id,coins:0,bestScore:0,races:0}})});
app.post('/api/racing/profile/:playerId',async(req,res)=>{try{const id=String(req.params.playerId).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,48);const profiles=await readJson(PROFILE_FILE,{});const old=profiles[id]||{playerId:id,coins:0,bestScore:0,races:0};const p={playerId:id,coins:Math.max(0,Math.floor(Number(req.body?.coins)??old.coins)),bestScore:Math.max(old.bestScore||0,Math.floor(Number(req.body?.bestScore)??old.bestScore||0)),races:Math.max(old.races||0,Math.floor(Number(req.body?.races)??old.races||0)),updatedAt:new Date().toISOString()};profiles[id]=p;await writeJson(PROFILE_FILE,profiles);res.json({ok:true,profile:p})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/chat',async(req,res)=>{try{const message=String(req.body?.message||'').trim();if(!message)return res.status(400).json({ok:false,error:'message is required'});const c=getClient();const r=await c.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6',input:[{role:'system',content:'You are LUMIRA AI. Answer clearly. Do not reveal secrets.'},{role:'user',content:message}]});res.json({ok:true,output:String(r.output_text||'').trim()})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/plan',async(req,res)=>{try{const c=getClient();const r=await c.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6',input:String(req.body?.instruction||'')});res.json({ok:true,plan:r.output_text})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/workspace/read',async(req,res)=>{try{res.json({ok:true,path:req.body.path,content:await fs.readFile(safePath(String(req.body.path||'')),'utf8')})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.post('/api/workspace/write',async(req,res)=>{try{const p=safePath(String(req.body?.path||''));await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,String(req.body?.content??''),'utf8');res.json({ok:true})}catch(e){res.status(400).json({ok:false,error:e.message})}});
app.post('/api/build',async(_q,res)=>{const r=await runCommand(BUILD_COMMAND,WORKSPACE_ROOT);res.status(r.ok?200:422).json({ok:r.ok,command:BUILD_COMMAND,...r})});
app.post('/api/fix',async(req,res)=>{try{res.json({ok:true,analysis:await analyzeError(String(req.body?.instruction||''),String(req.body?.errorLog||''))})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/build-and-analyze',async(req,res)=>{const b=await runCommand(BUILD_COMMAND,WORKSPACE_ROOT);if(b.ok)return res.json({ok:true,stage:'build',build:b,analysis:null});res.status(422).json({ok:false,stage:'analysis',build:b,analysis:await analyzeError(String(req.body?.instruction||''),[b.stdout,b.stderr].join('\n').slice(-20000))})});
const port=Number(process.env.PORT||8787);const server=createServer(app);attachMultiplayer(server);server.listen(port,()=>console.log(`AI Developer Workspace backend listening on ${port}`));