package com.lumira.healthcare;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

public class FeatureActivity extends Activity {
    private static final int NAVY=Color.rgb(24,39,70),INK=Color.rgb(22,37,66),PURPLE=Color.rgb(92,79,214),CORAL=Color.rgb(255,112,102),BG=Color.rgb(247,248,252),MUTED=Color.rgb(112,123,147);
    private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
    private GradientDrawable bg(int c,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}
    private GradientDrawable outline(int fill,int stroke,int width,int r){GradientDrawable d=bg(fill,r);d.setStroke(dp(width),stroke);return d;}
    private TextView t(String s,float z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
    private LinearLayout.LayoutParams lp(int l,int top,int r,int bottom){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(top),dp(r),dp(bottom));return p;}
    @Override public void onCreate(Bundle b){super.onCreate(b);String title=getIntent().getStringExtra("title");if(title==null)title="LUMIRA";LinearLayout screen=new LinearLayout(this);screen.setOrientation(LinearLayout.VERTICAL);screen.setBackgroundColor(BG);ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(12),dp(18),dp(30));sv.addView(root);screen.addView(sv,new LinearLayout.LayoutParams(-1,0,1));TextView back=t("‹   Back to LUMIRA",16,PURPLE,true);back.setPadding(0,dp(8),0,dp(12));back.setOnClickListener(v->finish());root.addView(back);
        LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setPadding(dp(22),dp(22),dp(22),dp(20));hero.setBackground(bg(NAVY,28));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView ib=t(icon(title),26,Color.WHITE,true);ib.setGravity(Gravity.CENTER);ib.setBackground(bg(Color.rgb(57,73,108),16));top.addView(ib,new LinearLayout.LayoutParams(dp(50),dp(50)));top.addView(t("LUMIRA CARE",11,Color.rgb(175,190,220),true),new LinearLayout.LayoutParams(0,-2,1));hero.addView(top);hero.addView(t(title,28,Color.WHITE,true),lp(0,15,0,5));hero.addView(t(getDescription(title),14,Color.rgb(220,228,242),false));root.addView(hero);
        root.addView(t("Quick actions",21,INK,true),lp(0,22,0,7));for(String a:getActions(title)){LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(16),dp(14),dp(14),dp(14));c.setBackground(outline(Color.WHITE,Color.rgb(232,234,241),1,19));TextView check=t("✓",18,Color.rgb(50,160,125),true);check.setGravity(Gravity.CENTER);check.setBackground(bg(Color.rgb(232,249,242),14));c.addView(check,new LinearLayout.LayoutParams(dp(38),dp(38)));c.addView(t(a,14,INK,true),new LinearLayout.LayoutParams(0,-2,1));c.addView(t("›",25,MUTED,false));root.addView(c,lp(0,5,0,5));}
        LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.HORIZONTAL);info.setPadding(dp(16),dp(15),dp(16),dp(15));info.setBackground(bg(Color.rgb(242,240,255),18));info.addView(t("◇",22,PURPLE,true),new LinearLayout.LayoutParams(dp(35),dp(35)));info.addView(t("Verified providers\nPrivacy-first care",13,INK,true),new LinearLayout.LayoutParams(0,-2,1));root.addView(info,lp(0,16,0,0));TextView primary=t(primaryAction(title),16,Color.WHITE,true);primary.setGravity(Gravity.CENTER);primary.setPadding(0,dp(16),0,dp(16));primary.setBackground(bg(CORAL,18));primary.setOnClickListener(v->android.widget.Toast.makeText(this,"This workflow is ready for backend integration.",android.widget.Toast.LENGTH_SHORT).show());root.addView(primary,lp(0,16,0,7));TextView note=t("LUMIRA  •  Healthcare Door to Door",12,MUTED,false);note.setGravity(Gravity.CENTER);root.addView(note,lp(0,8,0,0));setContentView(screen);}
    private String icon(String s){if(s.contains("Pharmacy"))return"▣";if(s.contains("Emergency"))return"▱";if(s.contains("Home"))return"⌂";if(s.contains("Telemedicine"))return"◉";if(s.contains("Appointment"))return"▤";return"♙";}
    private String primaryAction(String s){if(s.contains("Emergency"))return"Request emergency support";if(s.contains("Pharmacy"))return"Browse medicines";if(s.contains("Appointment"))return"Book an appointment";if(s.contains("Telemedicine"))return"Start consultation setup";return"Find available care";}
    private String[] getActions(String s){if(s.contains("Pharmacy"))return new String[]{"Browse common medicines","Upload a prescription for review","Track medicine delivery"};if(s.contains("Emergency"))return new String[]{"Request a verified emergency doctor","Request an ambulance","Share your location with approved care"};if(s.contains("Appointments"))return new String[]{"View upcoming appointments","Choose date and time","Manage confirmation and reminders"};if(s.contains("Home Healthcare"))return new String[]{"Request a home visit","Choose nursing or caregiver support","Schedule home sample collection"};if(s.contains("Telemedicine"))return new String[]{"Find available doctors","Prepare consent and consultation","Keep consultation records"};return new String[]{"Browse doctors by specialty","View doctor profiles and availability","Start the appointment workflow"};}
    private String getDescription(String s){if(s.contains("Doctor Care"))return"Find doctors by specialty, review availability and prepare your consultation.";if(s.contains("Appointments"))return"Manage consultations, dates, reminders and confirmations.";if(s.contains("Pharmacy"))return"Order medicines from verified pharmacies and keep prescriptions organized.";if(s.contains("Emergency"))return"A fast entry point for emergency care, ambulance requests and approved location sharing.";if(s.contains("Home Healthcare"))return"Bring nursing, caregiver and home-visit services closer to your doorstep.";if(s.contains("Telemedicine"))return"Prepare for a secure digital consultation with an available healthcare provider.";return"LUMIRA • Healthcare Door to Door";}
}
